### PR TITLE
Added Pending Uninstalls Widget for Munki

### PR DESCRIPTION
**Pull request by WardsParadox**
request based on:
https://github.com/munkireport/munkireport-php/issues/1178

### CODE REVIEW

**Comment by bochoven** [comment]
Please undo the rename of `pending_munki`, that name has been used for ages (default dashboard)

**Comment by WardsParadox** [comment]
@bochoven Done dealio :)

**Comment by bochoven** [comment]
Ehh, and pull against wip

**Comment by WardsParadox** [comment]
There is no wip on the managedinstalls module 😬

**Comment by bochoven** [comment]
Haha, silly me! I need more coffee!

**Comment by WardsParadox** [comment]
All good! More ☕️ your way!

**Comment by WardsParadox** [comment]
I think my VSCode might be borked I changed those but it didn't add them into the commit. Sorry bochoven!

**Pull request merged**
